In [3]:
import yfinance as yf
import threading
from openpyxl import load_workbook
import pandas as pd

workbook = load_workbook("StockData.xlsx")
sheet = workbook.active

def get_stats(ticker, row_count):
	info = yf.Tickers(ticker).tickers[ticker].info
	update_stock_price(info['currentPrice'], row_count)
	# print(info['currentPrice'])

def update_stock_price(price, row_count):
	# write the stock price to the cell values of column B
	sheet.cell(row=row_count, column=2).value = price

	# sheet.cell(row=row_count, column=2).value = price
	print(f"updated::{price}::{row_count}")
	workbook.save("StockData.xlsx")

if __name__ == '__main__':
	row_count = 2
	while True:
		# Read the cell values of column A
		ticker = sheet.cell(row=row_count, column=1).value
		if ticker is None:
			break

		thread = threading.Thread(target=get_stats, args=[ticker, row_count]).start()
		row_count += 1
		# Get and update the stock price

updated::0.0325::8
updated::0.1375::5
updated::0.335::4
updated::2447::10
updated::0.283::6
updated::270.02::9
updated::71.79::3
updated::2291.28::11
updated::145.38::2
updated::0.455::7

In [4]:
	df = pd.DataFrame(sheet.values)
	df

         0            1           2         3
0   Ticker  Stock Value  Investment    Profit
1     AAPL       145.38        1000    =B2/C2
2     ORCL        71.79        1000    =B3/C3
3   PREM.L        0.335        1000    =B4/C4
4   UKOG.L       0.1375        1000    =B5/C5
5    KOD.L        0.283        1000    =B6/C6
6    TOM.L        0.455        1000    =B7/C7
7   VELA.L       0.0325        1000    =B8/C8
8     MSFT       270.02        1000    =B9/C9
9     AMZN         2447        1000  =B10/C10
10    GOOG      2291.28        1000  =B11/C11
11    None         None        None      None